### ISSUE TITLE
nbm of last version?

### ISSUE THREAD

**Issue by mattbrun** [williballenthin/Autopsy-WindowsRegistryContentViewer#3]
Hello Willi,
I was wondering if it would be possible to have an already built nbm plugin of the last repo version.

Thanks for your hard work!
M.

**Comment by williballenthin** [comment]
hey @mattbrun 

Unfortunately, I don't have a build of the latest version (its been a couple years, and I've since refreshed my laptop). However, I believe Basis Tech as taken over this project, so they may have a newer build. @bcarrier?

**Comment by mattbrun** [comment]
Hi @williballenthin,
Thanks for your response! It's complicated for me as well to download all the dev build platform now...
We'll see.

**Comment by bcarrier** [comment]
@mattbrun you can get it from here:

https://github.com/sleuthkit/Autopsy-WindowsRegistryContentViewer/releases

It's actually included in the next Autopsy release, which should be out next week.

**Comment by williballenthin** [comment]
thanks @bcarrier !

**Comment by mattbrun** [comment]
Hi @williballenthin,
Thanks for your response! It's complicated for me as well to download all the dev build platform now...
We'll see what I'll be able to do.
Cheers
